### ISSUE TITLE
Binder not working?

### ISSUE THREAD

**Issue by danieljwilson** [ljchang/dartbrains#12]
![image](https://user-images.githubusercontent.com/7377893/59121785-0f018b00-8927-11e9-8d13-7e3585d70f77.png)

**Comment by ljchang** [comment]
I never actually tested the binder version.  Looks like a typo on requirements.  Fixed that and will see if it works for me.

**Comment by ljchang** [comment]
@danieljwilson:  Looks like it is working again.  Thanks for catching another bug!
