### ISSUE TITLE
Streamline book deployment

### ISSUE THREAD

**Issue by ljchang** [ljchang/dartbrains#31]
It would be great to streamline deployment of the book. This should be fairly straightforward, i just haven't had time to look into it.  There are at least two things we should do.

1) fix the CNAME issue so that we do not manually need to add the dartbrains.org domain name in the github settings after synching to the gh-pages branch. `ghp-import -n -p -f -c CNAME _build/html`  should be doing this, but it might have something to do with an improperly specified CNAME file.

2) auto build book and sync to gh-pages branch using a webhook via continuous integration with TravisCI or CircleCI. This whole process could easily be automated.

**Comment by wasita** [comment]
@ljchang 
to address #2, i want to create a github action for this, but in order to do that i'm p sure there needs to be an action secret generated for this repo. anyway I've started the github action here --> https://github.com/ljchang/dartbrains/pull/33

**Comment by wasita** [comment]
- commit where github action yaml file was added: b047708ed33331ec4c7f21a04de5cbd81ffc5f2d
- commit where jupyter-book was added to requirements in order for github action to run successfully: 092f38023c4ff730e639d02d7e5fb21d551cc5e0

**Comment by wasita** [comment]
- commit testing a trivial change to ensure gh action works as expected: 50f6e7df005a8b1afb90474f4773d7eba7fcf128
